[package]
name = "problem_solving"
version = "0.1.0"
authors = ["Jang Whemoon <palindrom615@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "blank"
path = "src/blank.rs"

[[bin]]
name = "boj15329"
path = "src/boj15329.rs"

[[bin]]
name = "boj2296"
path = "src/boj2296.rs"
